### ISSUE TITLE
Opening images

### ISSUE THREAD

**Issue by ghost** [tuqqu/tui-chan#1]
It would be nice to be able to directly open images or links in default web browser when pressing enter key or with a shortcut key . I dont know much about coding , so I dont know if it is possible , but I wanted to ask anyway .

**Comment by tuqqu** [comment]
Hey! That's a nice idea.
I've just pushed an update that introduces this feature:

`"o"` opens the link in browser
`control + "o"` opens the media only

Have a look at the latest [release](https://github.com/tuqqu/tui-chan/releases/tag/v0.2)
