### ISSUE TITLE
Word wrap does not work

### ISSUE THREAD

**Issue by nick-The-One** [tuqqu/tui-chan#2]
Words get cut off in long posts. Does not seem to be affected by terminal window size. Works fine in fullscreen view.
<img width="1168" alt="Screenshot 2022-06-22 at 17 30 18" src="https://user-images.githubusercontent.com/51474587/175071395-4ca8ff19-95e1-4161-bd73-2133bd440a2f.png">

**Comment by tuqqu** [comment]
Fixed in the [v0.5 release](https://github.com/tuqqu/tui-chan/releases/tag/v0.5)
