### ISSUE TITLE
Vim keybinds?

### ISSUE THREAD

**Issue by dxrcy** [tuqqu/tui-chan#3]
Is there a way to change keybinds, or use vim keybinds?
if not, no worry!

**Comment by tuqqu** [comment]
Currently, key bindings are hardcoded. It'd be nice to add such a feature tho.

**Comment by dxrcy** [comment]
I might make a pr

**Comment by tuqqu** [comment]
implemented in #4 ([release](https://github.com/tuqqu/tui-chan/releases/tag/v0.4))

Many thanks to @darccyy
